name: Release protector
on:
  pull_request:
    types: [ closed, edited, opened, synchronize, ready_for_review, labeled, unlabeled]
    branches: 
      # only run on branches targeting the `main` branch.
      - main

jobs:
  protect-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check date and labels
        id: check-date-and-labels
        run: |
          has_label="${{contains(github.event.pull_request.labels.*.name, 'i-acknowledge-this-goes-into-the-release')}}"
          today=$(date +'%Y%m%d%H%M')
          current_month=$(date +'%B')
          current_year=$(date +'%Y')
          release_date=$(date -d "${current_month} 21, ${current_year}" +'%Y%m%d0000')
          release_date_human=$(date -d "${current_month} 21, ${current_year}" +'%Y-%m-%d-00:00')

          if [ "$today" -gt "$release_date" ]; then
            if [ "$has_label" = "true" ]; then
              echo "✅ Label 'i-acknowledge-this-goes-into-the-release' is present"
              exit 0
            else 
              echo "❌ Label 'i-acknowledge-this-goes-into-the-release' is absent"
              echo "👉 We're in the next Sourcegraph release code freeze period. If you are 100% sure your changes should get released or provide no risk to the release, add the label your PR with 'i-acknowledge-this-goes-into-the release'"
              exit 1
            fi
          else
            echo "📅 Not enabled, we're not yet on $release_date_human and release code freeze has not started yet." 
            exit 0
          fi
